apiVersion: v2
name: access-control-service
description: A Helm library chart for Access Control Service
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: ingress-nginx
    version: 4.15.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: keycloak
    version: 25.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: keycloak.enabled
  - name: postgresql
    version: 18.5.11
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: gravitino
    version: 1.3.0
    repository: "file://../../../../../apache/gravitino/dev/charts/gravitino"
    condition: gravitino.enabled
  - name: polaris
    version: 1.3.0-incubating
    repository: https://downloads.apache.org/incubator/polaris/helm-chart/
    condition: polaris.enabled
  - name: unitycatalog
    alias: unity-catalog
    version: 0.0.1-pre.1
    repository: "file://../../../../../unitycatalog/unitycatalog/helm"
    condition: unity-catalog.enabled
  - name: hive-metastore
    version: 0.2.0
    repository: https://hevaweb.github.io/heva-helm-charts/
    condition: hive-metastore.enabled
  - name: cert-manager
    version: 1.14.4
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: acs-backend
    version: 0.1.0
    repository: "file://../../../../acs-backend/src/main/helm/acs-backend"
    condition: acs-backend.enabled
  - name: frontend
    alias: acs-ui
    version: 0.1.0
    repository: "file://../../../../acs-ui/frontend/helm/frontend"
    condition: acs-ui.enabled
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: prometheus
    version: 28.14.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: opentelemetry-collector
    version: 0.147.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
