apiVersion: v2
name: access-control-service
description: A Helm library chart for Access Control Service
type: library
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: ingress-nginx
    version: 4.10.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: keycloak
    version: 21.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: keycloak.enabled
  - name: postgresql
    version: 12.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: gravitino
    version: 0.1.0
    repository: https://datastrato.github.io/helm-charts
    condition: gravitino.enabled
  - name: polaris
    version: 0.1.0
    repository: https://polaris-catalog.io/helm-charts
    condition: polaris.enabled
  - name: unity-catalog
    version: 0.1.0
    repository: https://unitycatalog.github.io/helm-charts
    condition: unity-catalog.enabled
  - name: hive-metastore
    version: 0.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: hive-metastore.enabled
  - name: cert-manager
    version: 1.14.4
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: acs-backend
    version: 0.1.0
    repository: https://rhlowery.github.io/acs-backend
    condition: acs-backend.enabled
  - name: acs-ui
    version: 0.1.0
    repository: https://rhlowery.github.io/acs-ui
    condition: acs-ui.enabled
