apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values "unity-catalog").auth.clientSecretName | default "unity-catalog-oidc-secret" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  clientId: "unity-catalog-server"
  clientSecret: "{{ (index .Values "unity-catalog").auth.clientSecret | default "REPLACE_WITH_KEYCLOAK_SECRET" }}"
