apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.secretName | default "postgresql-app-user" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username | default "access_control_user" }}
  password: {{ .Values.postgresql.auth.password | default "user_password" }}
