name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Build, Version, and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
 
      - name: Setup Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Calculate Next Version
        id: versioning
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          default_bump: patch

      - name: Update Version Configurations
        env:
          NEW_VERSION: ${{ steps.versioning.outputs.new_version }}
        run: |
          # 1. Update Maven pom.xml files
          mvn versions:set -DnewVersion=${NEW_VERSION} -DgenerateBackupPoms=false
          
          # 2. Update Helm Chart version
          sed -i "s/^version:.*/version: ${NEW_VERSION}/" helm/src/main/helm/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${NEW_VERSION}\"/" helm/src/main/helm/Chart.yaml
          
          # 3. Generate Changelog
          npx -y conventional-changelog-cli -p angular -i CHANGELOG.md -s

      - name: Branch, Commit and Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ steps.versioning.outputs.new_version }}
          NEW_TAG: ${{ steps.versioning.outputs.new_tag }}
        run: |
          # Checkout new release branch
          git checkout -b release/${NEW_VERSION}
          
          # Add modified files
          git add "pom.xml" "*/pom.xml" "helm/src/main/helm/Chart.yaml" "CHANGELOG.md"
          
          # Only commit and push if there are actual changes
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
            exit 0
          fi
          
          # Commit the changes
          git commit -m "chore(release): system version ${NEW_VERSION}"
          
          # Tag the release
          git tag -a ${NEW_TAG} -m "Release ${NEW_TAG}"
          
          # Push the release branch
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin release/${NEW_VERSION}
          
          # Push the tag
          git push origin ${NEW_TAG}
